#!/usr/bin/env python3
"""Visualize FFT division sweep outcomes using two-bit flag semantics.

Each case exported by ``run_fft_division_sweep.py`` now includes two boolean
flags: ``finished_flag`` (1 if the run wrapped before timeout) and
``quality_flag`` (1 if the result was "good" — a PASS or an active timeout).
These are combined into four canonical labels:

* ``finished_good`` – completed, passed validation.
* ``finished_bad`` – completed, failed validation.
* ``timeout_active`` – timed out with active work in the tail logs.
* ``timeout_bad`` – timed out with panic/idle/no evidence of progress.

This plotting helper renders three coordinated panels based on those labels:

1. Stacked bar chart showing how canonicalized result types distribute per
    ``window_power`` bucket.
2. Runtime scatter plot colored by the flag combination and shaped by status
    (PASS/FAIL/TIMEOUT) for quick at-a-glance triage.
3. A correlation heatmap (window power vs. working window) that encodes the
    average ``quality_flag`` for each grid cell together with completion rates.
"""

from __future__ import annotations

import argparse
import importlib
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, List, Sequence

import numpy as np

plt: Any | None = None
_to_hex = None
_patches = None

FLAG_COMBO_LABELS = {
    (0, 0): "timeout_bad",
    (0, 1): "timeout_active",
    (1, 0): "finished_bad",
    (1, 1): "finished_good",
}

FLAG_LABEL_ORDER = [
    "finished_good",
    "finished_bad",
    "timeout_active",
    "timeout_bad",
    "unknown_flag_combo",
]

FLAG_LABEL_DESCRIPTIONS = {
    "finished_good": "finished + pass",
    "finished_bad": "finished + fail",
    "timeout_active": "timeout + active tail",
    "timeout_bad": "timeout + panic/idle/unknown",
    "unknown_flag_combo": "unrecognized flag combo",
}

FLAG_LABEL_COLORS = {
    "finished_good": "#2ca02c",
    "finished_bad": "#d62728",
    "timeout_active": "#1f77b4",
    "timeout_bad": "#ff7f0e",
    "unknown_flag_combo": "#7f7f7f",
}


def ensure_matplotlib() -> None:
    global plt, _to_hex, _patches
    if plt is not None and _to_hex is not None and _patches is not None:
        return
    try:
        plt = importlib.import_module("matplotlib.pyplot")
        colors_mod = importlib.import_module("matplotlib.colors")
        _to_hex = colors_mod.to_hex
        _patches = importlib.import_module("matplotlib.patches")
    except ImportError as exc:  # pragma: no cover - environment guard
        raise SystemExit(
            "matplotlib is required for plotting. Install it via `pip install matplotlib`."
        ) from exc

DEFAULT_COLOR = "#7f7f7f"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("output/fft_division_sweep.json"),
        help="Path to the JSON summary generated by run_fft_division_sweep.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to save the matplotlib figure (PNG recommended).",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=150,
        help="Figure DPI when exporting to a file (default: 150).",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the figure in an interactive window after rendering.",
    )
    return parser.parse_args()


def load_cases(path: Path) -> tuple[List[dict], Dict]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if isinstance(payload, dict) and "cases" in payload:
        cases = payload.get("cases", [])
    elif isinstance(payload, list):
        cases = payload
        payload = {"cases": cases}
    else:
        raise SystemExit(
            "Unrecognized JSON structure. Expected a dict with 'cases' or a list of case dicts."
        )
    if not cases:
        raise SystemExit("No cases found in the provided JSON summary.")
    return cases, payload


def normalize_window_power(value) -> str:
    return "default" if value is None else str(value)


def normalize_working_window(value) -> str:
    return "default" if value is None else str(value)


def _category_sort_key(label: str) -> tuple[int, float | str]:
    try:
        return (0, float(label))
    except ValueError:
        return (1, label)


def canonicalize_plot_result_type(rtype: str | None) -> str:
    if not rtype:
        return "unknown"
    parts = rtype.split("|")
    if not parts:
        return "unknown"
    status, *tokens = parts
    filtered = [token for token in tokens if not token.startswith("patience=")]
    if not filtered:
        filtered = ["none"]
    return "|".join([status] + filtered)


def derive_flag_label(case: dict) -> str:
    label = case.get("flag_label")
    if label:
        return label
    try:
        finished = int(case.get("finished_flag", 0) or 0)
    except (TypeError, ValueError):
        finished = 0
    try:
        quality = int(case.get("quality_flag", 0) or 0)
    except (TypeError, ValueError):
        quality = 0
    return FLAG_COMBO_LABELS.get((finished, quality), "unknown_flag_combo")


def derive_result_type_order(cases: Sequence[dict]) -> List[str]:
    counts = Counter(
        case.get("_plot_result_type", canonicalize_plot_result_type(case.get("result_type")))
        for case in cases
    )
    if not counts:
        return ["unknown"]
    ordered = [rtype for rtype, _ in counts.most_common()]
    return ordered


def assign_result_type_colors(result_types: Sequence[str]) -> Dict[str, str]:
    ensure_matplotlib()
    cmap = plt.cm.get_cmap("tab20", max(len(result_types), 1))
    colors: Dict[str, str] = {}
    for idx, rtype in enumerate(result_types):
        colors[rtype] = _to_hex(cmap(idx))  # type: ignore[arg-type]
    return colors


def stacked_bar(
    ax,
    cases: Sequence[dict],
    result_type_order: Sequence[str],
) -> Sequence[str]:
    categories = sorted(
        {normalize_window_power(case.get("window_power")) for case in cases},
        key=_category_sort_key,
    )
    if not categories:
        raise SystemExit("Window power categories could not be derived from the JSON data.")
    cat_index = {cat: idx for idx, cat in enumerate(categories)}
    counts = defaultdict(lambda: [0] * len(categories))
    for case in cases:
        rtype = case.get("_plot_result_type", canonicalize_plot_result_type(case.get("result_type")))
        idx = cat_index[normalize_window_power(case.get("window_power"))]
        counts[rtype][idx] += 1

    colors = assign_result_type_colors(result_type_order)
    bottoms = [0] * len(categories)
    for rtype in result_type_order:
        values = counts.get(rtype)
        if not values or all(v == 0 for v in values):
            continue
        ax.bar(
            categories,
            values,
            bottom=bottoms,
            label=rtype,
            color=colors.get(rtype, DEFAULT_COLOR),
        )
        bottoms = [b + v for b, v in zip(bottoms, values)]

    ax.set_title("Result types per window power")
    ax.set_xlabel("window_power")
    ax.set_ylabel("case count")
    ax.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), fontsize="small")
    return categories


def scatter_runtime(
    ax,
    cases: Sequence[dict],
    categories: Sequence[str],
) -> set[str]:
    cat_index = {cat: idx for idx, cat in enumerate(categories)}
    status_markers = {
        "PASS": ("o", "pass"),
        "FAIL": ("X", "fail"),
        "TIMEOUT": ("D", "timeout"),
    }
    groups: Dict[str, Dict[str, List[float | str]]] = {}
    observed_flags: set[str] = set()
    for case in cases:
        status = case.get("status", "unknown")
        group = groups.setdefault(status, {"x": [], "y": [], "colors": []})
        idx = cat_index[normalize_window_power(case.get("window_power"))]
        group["x"].append(idx)
        group["y"].append(case.get("duration", 0.0))
        flag_label = case.get("_flag_label") or derive_flag_label(case)
        observed_flags.add(flag_label)
        color = FLAG_LABEL_COLORS.get(flag_label, DEFAULT_COLOR)
        group["colors"].append(color)

    for status, payload in groups.items():
        if not payload["x"]:
            continue
        marker, label = status_markers.get(status, ("o", status.lower()))
        ax.scatter(
            payload["x"],
            payload["y"],
            c=payload["colors"],
            marker=marker,
            s=80,
            edgecolors="#333333",
            linewidths=0.6,
            alpha=0.85,
            label=label,
        )

    ax.set_xticks(range(len(categories)))
    ax.set_xticklabels(categories)
    ax.set_xlabel("window_power")
    ax.set_ylabel("duration (s)")
    ax.set_title("Runtime vs. flag combination")
    ax.grid(True, linestyle="--", linewidth=0.4, alpha=0.5)

    handles, labels = ax.get_legend_handles_labels()
    legend_status = None
    if handles:
        legend_status = ax.legend(
            loc="upper left",
            bbox_to_anchor=(1.01, 1.0),
            fontsize="small",
        )
        ax.add_artist(legend_status)
    flag_handles = []
    for label in FLAG_LABEL_ORDER:
        if label not in observed_flags:
            continue
        desc = FLAG_LABEL_DESCRIPTIONS.get(label, label)
        handle = _patches.Patch(
            facecolor=FLAG_LABEL_COLORS.get(label, DEFAULT_COLOR),
            edgecolor="#333333",
            label=f"{label} — {desc}",
        )
        flag_handles.append(handle)
    if flag_handles:
        ax.legend(
            handles=flag_handles,
            loc="upper left",
            bbox_to_anchor=(1.01, 0.5),
            fontsize="small",
            title="flag combos",
        )
    return observed_flags


def heatmap_quality_correlations(
    ax,
    cases: Sequence[dict],
    *,
    window_categories: Sequence[str],
) -> None:
    y_categories = sorted(
        {normalize_working_window(case.get("working_window")) for case in cases},
        key=_category_sort_key,
    )
    if not y_categories:
        y_categories = ["default"]

    grid: Dict[tuple[str, str], List[tuple[int, int]]] = defaultdict(list)
    for case in cases:
        wp = normalize_window_power(case.get("window_power"))
        ww = normalize_working_window(case.get("working_window"))
        try:
            finished_flag = int(case.get("finished_flag", 0) or 0)
        except (TypeError, ValueError):
            finished_flag = 0
        try:
            quality_flag = int(case.get("quality_flag", 0) or 0)
        except (TypeError, ValueError):
            quality_flag = 0
        grid[(wp, ww)].append((finished_flag, quality_flag))

    matrix = np.full((len(y_categories), len(window_categories)), np.nan, dtype=float)
    finish_matrix = np.full_like(matrix, np.nan)
    counts = np.zeros_like(matrix)
    x_index = {label: idx for idx, label in enumerate(window_categories)}
    y_index = {label: idx for idx, label in enumerate(y_categories)}

    for (wp, ww), entries in grid.items():
        if wp not in x_index or ww not in y_index or not entries:
            continue
        yi = y_index[ww]
        xi = x_index[wp]
        finished_sum = sum(entry[0] for entry in entries)
        quality_sum = sum(entry[1] for entry in entries)
        count = len(entries)
        counts[yi, xi] = count
        matrix[yi, xi] = quality_sum / count
        finish_matrix[yi, xi] = finished_sum / count

    cmap = plt.cm.Greens
    im = ax.imshow(
        matrix,
        cmap=cmap,
        aspect="auto",
        vmin=0.0,
        vmax=1.0,
        origin="upper",
    )
    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label("avg quality_flag (1 = good)")

    for yi, row in enumerate(matrix):
        for xi, value in enumerate(row):
            if np.isnan(value):
                continue
            count = int(counts[yi, xi])
            finish_rate = finish_matrix[yi, xi]
            ax.text(
                xi,
                yi,
                f"q={value:.2f}\nfin={finish_rate:.2f}\n(n={count})",
                ha="center",
                va="center",
                fontsize=8,
                color="black",
            )

    ax.set_xticks(range(len(window_categories)))
    ax.set_xticklabels(window_categories)
    ax.set_yticks(range(len(y_categories)))
    ax.set_yticklabels(y_categories)
    ax.set_xlabel("window_power")
    ax.set_ylabel("working_window")
    ax.set_title("Window vs working window (quality + finish rates)")


def main() -> None:
    args = parse_args()
    cases, payload_meta = load_cases(args.input)
    ensure_matplotlib()
    for case in cases:
        case["_plot_result_type"] = canonicalize_plot_result_type(case.get("result_type"))
        case["_flag_label"] = derive_flag_label(case)
    result_type_order = derive_result_type_order(cases)

    fig = plt.figure(figsize=(14, 22))
    gs = fig.add_gridspec(3, 1, height_ratios=[1.2, 1.8, 2.1], hspace=0.35)
    ax_bar = fig.add_subplot(gs[0])
    ax_scatter = fig.add_subplot(gs[1])
    ax_heat = fig.add_subplot(gs[2])

    categories = stacked_bar(ax_bar, cases, result_type_order)
    scatter_runtime(ax_scatter, cases, categories)
    heatmap_quality_correlations(
        ax_heat,
        cases,
        window_categories=categories,
    )
    fig.suptitle("FFT Division Sweep Outcome Overview", fontsize=16)
    fig.tight_layout(rect=(0, 0.03, 1, 0.98))

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.output, dpi=args.dpi, bbox_inches="tight")
        print(f"Saved visualization to {args.output}")

    if args.show:
        plt.show()
    else:
        plt.close(fig)


if __name__ == "__main__":
    main()
